export const REFRESH_DATA_TO_STORE = "REFRESH_DATA_TO_STORE";
export const GET_DATA_FROM_BASE = "GET_DATA_FROM_BASE";
export const CHANGE_MIDDLE_COUNT = "CHANGE_MIDDLE_COUNT";
export const CHANGE_ACTIVE_BARGAINING = "CHANGE_ACTIVE_BARGAINING";
export const ADD_TENDER_TO_STORE = "ADD_TENDER_TO_STORE";
