export const TEST = 'TEST'
export const CREATEAUCTION = 'CREATEAUCTION '
export const LOADEDAUCTION = 'LOADEDAUCTION '
export const ALLAUCTION = 'ALLAUCTION '
export const USERINAUCTION = 'USERINAUCTION '

